# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Zahra Amirmahani
title: Data Engineer
email: zahra.m245@gmail.com
# email_title: Email (Email title override)
phone: 0989377883218
# phone_title: Phone (Phone title override)

# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: zahramahani
linkedin_username: zahra-mahani-9290aa141
about_profile_image: images/zahra.png
about_content: I'm zahra Amirmahani, 25 years old, from Kerman/Iran. my Research Interests are Data mining, Big data and Natural Language Processing.I have been working in the data engineering and data analysis department of the <a href="https://www.partdp.ir"> part </a> company for 2 years besides of educating in MSC.


content:
  - title: Experiances # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Summer school of data
        quote: >
          Mashhad Municipality
          Jul 2020 - Jul 2020
        description: | # this will include new lines to allow paragraphs
          I participated in this school and could learn about algorithem - Machine learning methods - big data - softwares like tableau relating to data.
          
          
         # ![certificate](/images/z amirmahani.jpg)
          
      - layout: left
        title: Javaspring internship
        quote: >
          FANAP
          Jun 2020 - Jul 2020
        description: | # this will include new lines to allow paragraphs
          In this enternship I could learn jdbc, hibernate and creating web service with java.
      
      - layout: left
        title: Teaching Assistant
        quote: >
          Ferdowsi University of Mashhad
          Feb 2020 - Jun 2020
        description: | # this will include new lines to allow paragraphs
          Bigdata course teached by Dr.ensan
          
      - layout: left
        title: Data engineer - Data analyst 
        quote: >
          working in data engineering and data analysis section of <a href="https://www.partdp.ir"> part </a> company for 2 years.
           (Oct 2019 - Present)
        description: | # this will include new lines to allow paragraphs
          In this section, me and my co-workers are working on databases (postgresql - mongodb - redis - sqlite) and trying to manage replicas,failover and fail back.
          During this 2 years I colud improve the search speed of postgresql with writing custom parser, analysing some data and working on big data (hdfs - map reduce - yarn of hadoop and spark).
          
      - layout: left
        title: Software development  internship
        quote: >
          Jul 2019 - Sep 2019
        description: | # this will include new lines to allow paragraphs
          I participated in a software development internship held in summer 2019 at Part college and in the end they hired me in the data section of this company as i wanted.
          I could learn node js in backend part. aureilla- html-css- sass in frontend part and postgresql as database.
          
      
      - layout: left
        title: Teaching Assistant
        quote: >
          Ferdowsi University of Mashhad
          Oct 2018 - Jan 2019
        description: | # this will include new lines to allow paragraphs
          signal processing teached by Dr.sadoghi.
           
           
  - title: Projects
    layout: list
    content:   
      - layout: left
        title: Master Thesis
        sub_title: Feb 2020 - present
        description: | # this will include new lines to allow paragraphs
          finding entity  form text  input with the help of deep neurall networks.
          
      - layout: left
        title: NLP on corona data
        sub_title: 2020
        description: | # this will include new lines to allow paragraphs
          we processed some data of corona, which were the qustions asked by people in social medias.
          
      - layout: left
        title: BSC project
        sub_title: Feb 2018 - Sep 2019
            
        description: | # this will include new lines to allow paragraphs.
          Examining the pattern of electricity consumption with the help of machine learning.
          Implementation was on matlab.
          
      - layout: left
        title: Baby care doll
        sub_title: 2017
        description: | # this will include new lines to allow paragraphs
           2 arduino and 2 nrf were used, which could communicate to each other. one in a doll, listening, and if the baby would cry then the other arduino would start alerting. 
          
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: MSC
        sub_title: software engineering at Ferdowsi University of Mashhad
        caption: Sep 2019 - Present
        quote: >
          Accepted in the entrance exam as well as brilliant talent (7th person out of 72 class mate in BSC) 
        description: | # this will include new lines to allow paragraphs
          Grade: 17.78 (3.74/4)\
          Passed Courses: 
          - advanced Information Reterival 
          - semantic web 
          - search engine 
          - neural network 
          - deep learning 
          - knowlege base management 
          - advanced database 
          - advanced algorithem
      - layout: top-left  
        title: BSC
        sub_title: software engineering at Ferdowsi University of Mashhad
        caption: Sep 2015 - Sep 2019
        quote: >
          Accepted in the entrance exam (2080 th person out of 50000 people) 
        description: | # this will include new lines to allow paragraphs
          Grade: 17.60\
          Major Passed Courses: 
          - data analysis
          - machine learning
          - security
          - software test
          - software design
          
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
    
      - Java - Spring
      - Big Data
      - Nodejs
      - DataAnalysis
      - python
        - pytorch
        - sklearn
        - pandas
        - numpy
        - matplotlib
      - Software test
      - C
      - Git
      - PostgreSql - Redis - Sqlite - Mongodb
      - Aureilla - html - css - sass
      - Tableau
      - Visual Paradigm
      - linux (ubuntu)
      
  - title: Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      - drawing (water color - hyper real), sculpturing
      - riding a bike and playing basket ball

      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
